# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn clean package

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      # - run: mvn integration-test

      # Store the jars as artifacts to use in update site
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc/target/org.eclipse.epsilon.emc.jdbc-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc-1.1.0-SNAPSHOT.jar

      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.feature/target/org.eclipse.epsilon.emc.jdbc.feature-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.feature-1.1.0-SNAPSHOT.jar
      
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.mysql/target/org.eclipse.epsilon.emc.jdbc.mysql-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.mysql-1.1.0-SNAPSHOT.jar
      
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.mysql.dependencies/target/org.eclipse.epsilon.emc.jdbc.mysql.dependencies-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.mysql.dependencies-1.1.0-SNAPSHOT.jar
      
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.mysql.dt/target/org.eclipse.epsilon.emc.jdbc.mysql.dt-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.mysql.dt-1.1.0-SNAPSHOT.jar
      
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.mysql.dt.feature/target/org.eclipse.epsilon.emc.jdbc.mysql.dt.feature-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.mysql.dt.feature-1.1.0-SNAPSHOT.jar
      
      - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.emc.jdbc.mysql.feature/target/org.eclipse.epsilon.emc.jdbc.mysql.feature-1.1.0-SNAPSHOT.jar
          destination: org.eclipse.epsilon.emc.jdbc.mysql.feature-1.1.0-SNAPSHOT.jar
      